/**
 * src/components/stv-line-chart/test-props.ts
 */
export default {
  axisLabelFontSize: 14,
  axisTickFontFamily: 'sans',
  axisTickFontSize: 10,
  barStroke: 'transparent',
  barStrokeWidth: 1,
  canvasHeight: 300,
  canvasWidth: 500,
  chartData: [
    {year: '1941', combatant: 'Germany', armament: 'Light Tank', produced: 943},
    {year: '1941', combatant: 'Germany', armament: 'Medium Tank', produced: 2680},
    {year: '1941', combatant: 'Germany', armament: 'Heavy Tank', produced: 0},
    {year: '1941', combatant: 'Soviet Union', armament: 'Light Tank', produced: 2321},
    {year: '1941', combatant: 'Soviet Union', armament: 'Medium Tank', produced: 3016},
    {year: '1941', combatant: 'Soviet Union', armament: 'Heavy Tank', produced: 1353},
    {year: '1941', combatant: 'US', armament: 'Light Tank', produced: 2591},
    {year: '1941', combatant: 'US', armament: 'Medium Tank', produced: 1430},
    {year: '1941', combatant: 'US', armament: 'Heavy Tank', produced: 0},
    {year: '1942', combatant: 'Germany', armament: 'Light Tank', produced: 1500},
    {year: '1942', combatant: 'Germany', armament: 'Medium Tank', produced: 3952},
    {year: '1942', combatant: 'Germany', armament: 'Heavy Tank', produced: 78},
    {year: '1942', combatant: 'Soviet Union', armament: 'Light Tank', produced: 9580},
    {year: '1942', combatant: 'Soviet Union', armament: 'Medium Tank', produced: 13473},
    {year: '1942', combatant: 'Soviet Union', armament: 'Heavy Tank', produced: 2635},
    {year: '1942', combatant: 'US', armament: 'Light Tank', produced: 10674},
    {year: '1942', combatant: 'US', armament: 'Medium Tank', produced: 15720},
    {year: '1942', combatant: 'US', armament: 'Heavy Tank', produced: 0},
    {year: '1943', combatant: 'Germany', armament: 'Light Tank', produced: 1811},
    {year: '1943', combatant: 'Germany', armament: 'Medium Tank', produced: 9050},
    {year: '1943', combatant: 'Germany', armament: 'Heavy Tank', produced: 740},
    {year: '1943', combatant: 'Soviet Union', armament: 'Light Tank', produced: 5512},
    {year: '1943', combatant: 'Soviet Union', armament: 'Medium Tank', produced: 19808},
    {year: '1943', combatant: 'Soviet Union', armament: 'Heavy Tank', produced: 1422},
    {year: '1943', combatant: 'US', armament: 'Light Tank', produced: 9024},
    {year: '1943', combatant: 'US', armament: 'Medium Tank', produced: 28164},
    {year: '1943', combatant: 'US', armament: 'Heavy Tank', produced: 0}
  ],
  chartId: 'my-stv-stacked-bar-chart',
  colorScheme: 'category10',
  gridlines: true,
  hideXAxis: false,
  hideXTicks: false,
  hideYAxis: false,
  hideYTicks: false,
  inverse: false,
  legend: true,
  legendFontSize: 12,
  legendWidth: 150,
  linearDomain: 'absolute',
  linearMetric: 'produced',
  linearTickFormat: 'localestring',
  marginBottom: 25,
  marginLeft: 25,
  marginRight: 25,
  marginTop: 25,
  maxBarWidth: 75,
  ordinalMetric: 'year',
  orientation: 'vertical',
  responsive: true,
  seriesMetric: 'combatant',
  tooltips: true,
  xLabel: 'Year',
  xTickSize: 2,
  yLabel: 'Production',
  yTickSize: 2
}
