/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  IfcStvBarChart,
} from './interfaces/IfcStvBarChart';
import {
  IfcStvLineChart,
} from './interfaces/IfcStvLineChart';
import {
  IfcStvPieChart,
} from './interfaces/IfcStvPieChart';
import {
  IfcStvStackedBarChart,
} from './interfaces/IfcStvStackedBarChart';

export namespace Components {
  interface StvBarChart {
    'axisLabelFontSize': number;
    'axisTickFontFamily': string;
    'axisTickFontSize': number;
    'barStroke': string;
    'barStrokeWidth': number;
    'canvasHeight': number;
    'canvasWidth': number;
    'chartData': IfcStvBarChart[];
    'chartId': string;
    'colorScheme': string;
    'gridlines': boolean;
    'hideXAxis': boolean;
    'hideXTicks': boolean;
    'hideYAxis': boolean;
    'hideYTicks': boolean;
    'inverse': boolean;
    'legend': boolean;
    'legendFontSize': number;
    'legendMetric': string;
    'legendWidth': number;
    'linearMetric': string;
    'linearTickFormat': string;
    'marginBottom': number;
    'marginLeft': number;
    'marginRight': number;
    'marginTop': number;
    'maxBarWidth': number;
    'ordinalMetric': string;
    'orientation': string;
    'responsive': boolean;
    'tooltips': boolean;
    'xLabel': string;
    'xTickSize': number;
    'yLabel': string;
    'yTickSize': number;
  }
  interface StvLineChart {
    'axisLabelFontSize': number;
    'axisTickFontFamily': string;
    'axisTickFontSize': number;
    'canvasHeight': number;
    'canvasWidth': number;
    'chartData': IfcStvLineChart;
    'chartId': string;
    'colorScheme': string;
    'gridlines': boolean;
    'hideXAxis': boolean;
    'hideXTicks': boolean;
    'hideYAxis': boolean;
    'hideYTicks': boolean;
    'interpolation': string;
    'inverse': boolean;
    'legend': boolean;
    'legendFontSize': number;
    'legendMetric': string;
    'legendWidth': number;
    'marginBottom': number;
    'marginLeft': number;
    'marginRight': number;
    'marginTop': number;
    'responsive': boolean;
    'strokeWidth': number;
    'tooltips': boolean;
    'vertices': boolean;
    'xLabel': string;
    'xMetric': string;
    'xTickFormat': string;
    'xTickSize': number;
    'yLabel': string;
    'yMetric': string;
    'yTickFormat': string;
    'yTickSize': number;
  }
  interface StvPieChart {
    'canvasHeight': number;
    'canvasWidth': number;
    'chartData': IfcStvPieChart;
    'chartId': string;
    'colorScheme': string;
    'innerRadius': number;
    'inverse': boolean;
    'legend': boolean;
    'legendFontSize': number;
    'legendMetric': string;
    'legendWidth': number;
    'marginBottom': number;
    'marginLeft': number;
    'marginRight': number;
    'marginTop': number;
    'responsive': boolean;
    'stroke': string;
    'strokeWidth': number;
    'tooltips': boolean;
    'valueFormat': string;
    'valueMetric': string;
  }
  interface StvStackedBarChart {
    'axisLabelFontSize': number;
    'axisTickFontFamily': string;
    'axisTickFontSize': number;
    'barStroke': string;
    'barStrokeWidth': number;
    'canvasHeight': number;
    'canvasWidth': number;
    'chartData': IfcStvStackedBarChart;
    'chartId': string;
    'colorScheme': string;
    'gridlines': boolean;
    'hideXAxis': boolean;
    'hideXTicks': boolean;
    'hideYAxis': boolean;
    'hideYTicks': boolean;
    'inverse': boolean;
    'legend': boolean;
    'legendFontSize': number;
    'legendWidth': number;
    'linearDomain': string;
    'linearMetric': string;
    'linearTickFormat': string;
    'marginBottom': number;
    'marginLeft': number;
    'marginRight': number;
    'marginTop': number;
    'maxBarWidth': number;
    'ordinalMetric': string;
    'orientation': string;
    'responsive': boolean;
    'seriesMetric': string;
    'tooltips': boolean;
    'xLabel': string;
    'xTickSize': number;
    'yLabel': string;
    'yTickSize': number;
  }
}

declare global {


  interface HTMLStvBarChartElement extends Components.StvBarChart, HTMLStencilElement {}
  var HTMLStvBarChartElement: {
    prototype: HTMLStvBarChartElement;
    new (): HTMLStvBarChartElement;
  };

  interface HTMLStvLineChartElement extends Components.StvLineChart, HTMLStencilElement {}
  var HTMLStvLineChartElement: {
    prototype: HTMLStvLineChartElement;
    new (): HTMLStvLineChartElement;
  };

  interface HTMLStvPieChartElement extends Components.StvPieChart, HTMLStencilElement {}
  var HTMLStvPieChartElement: {
    prototype: HTMLStvPieChartElement;
    new (): HTMLStvPieChartElement;
  };

  interface HTMLStvStackedBarChartElement extends Components.StvStackedBarChart, HTMLStencilElement {}
  var HTMLStvStackedBarChartElement: {
    prototype: HTMLStvStackedBarChartElement;
    new (): HTMLStvStackedBarChartElement;
  };
  interface HTMLElementTagNameMap {
    'stv-bar-chart': HTMLStvBarChartElement;
    'stv-line-chart': HTMLStvLineChartElement;
    'stv-pie-chart': HTMLStvPieChartElement;
    'stv-stacked-bar-chart': HTMLStvStackedBarChartElement;
  }
}

declare namespace LocalJSX {
  interface StvBarChart {
    'axisLabelFontSize'?: number;
    'axisTickFontFamily'?: string;
    'axisTickFontSize'?: number;
    'barStroke'?: string;
    'barStrokeWidth'?: number;
    'canvasHeight'?: number;
    'canvasWidth'?: number;
    'chartData'?: IfcStvBarChart[];
    'chartId'?: string;
    'colorScheme'?: string;
    'gridlines'?: boolean;
    'hideXAxis'?: boolean;
    'hideXTicks'?: boolean;
    'hideYAxis'?: boolean;
    'hideYTicks'?: boolean;
    'inverse'?: boolean;
    'legend'?: boolean;
    'legendFontSize'?: number;
    'legendMetric'?: string;
    'legendWidth'?: number;
    'linearMetric'?: string;
    'linearTickFormat'?: string;
    'marginBottom'?: number;
    'marginLeft'?: number;
    'marginRight'?: number;
    'marginTop'?: number;
    'maxBarWidth'?: number;
    'onStv-bar-chart-loaded'?: (event: CustomEvent<any>) => void;
    'ordinalMetric'?: string;
    'orientation'?: string;
    'responsive'?: boolean;
    'tooltips'?: boolean;
    'xLabel'?: string;
    'xTickSize'?: number;
    'yLabel'?: string;
    'yTickSize'?: number;
  }
  interface StvLineChart {
    'axisLabelFontSize'?: number;
    'axisTickFontFamily'?: string;
    'axisTickFontSize'?: number;
    'canvasHeight'?: number;
    'canvasWidth'?: number;
    'chartData'?: IfcStvLineChart;
    'chartId'?: string;
    'colorScheme'?: string;
    'gridlines'?: boolean;
    'hideXAxis'?: boolean;
    'hideXTicks'?: boolean;
    'hideYAxis'?: boolean;
    'hideYTicks'?: boolean;
    'interpolation'?: string;
    'inverse'?: boolean;
    'legend'?: boolean;
    'legendFontSize'?: number;
    'legendMetric'?: string;
    'legendWidth'?: number;
    'marginBottom'?: number;
    'marginLeft'?: number;
    'marginRight'?: number;
    'marginTop'?: number;
    'onStv-line-chart-loaded'?: (event: CustomEvent<any>) => void;
    'responsive'?: boolean;
    'strokeWidth'?: number;
    'tooltips'?: boolean;
    'vertices'?: boolean;
    'xLabel'?: string;
    'xMetric'?: string;
    'xTickFormat'?: string;
    'xTickSize'?: number;
    'yLabel'?: string;
    'yMetric'?: string;
    'yTickFormat'?: string;
    'yTickSize'?: number;
  }
  interface StvPieChart {
    'canvasHeight'?: number;
    'canvasWidth'?: number;
    'chartData'?: IfcStvPieChart;
    'chartId'?: string;
    'colorScheme'?: string;
    'innerRadius'?: number;
    'inverse'?: boolean;
    'legend'?: boolean;
    'legendFontSize'?: number;
    'legendMetric'?: string;
    'legendWidth'?: number;
    'marginBottom'?: number;
    'marginLeft'?: number;
    'marginRight'?: number;
    'marginTop'?: number;
    'onStv-pie-chart-loaded'?: (event: CustomEvent<any>) => void;
    'responsive'?: boolean;
    'stroke'?: string;
    'strokeWidth'?: number;
    'tooltips'?: boolean;
    'valueFormat'?: string;
    'valueMetric'?: string;
  }
  interface StvStackedBarChart {
    'axisLabelFontSize'?: number;
    'axisTickFontFamily'?: string;
    'axisTickFontSize'?: number;
    'barStroke'?: string;
    'barStrokeWidth'?: number;
    'canvasHeight'?: number;
    'canvasWidth'?: number;
    'chartData'?: IfcStvStackedBarChart;
    'chartId'?: string;
    'colorScheme'?: string;
    'gridlines'?: boolean;
    'hideXAxis'?: boolean;
    'hideXTicks'?: boolean;
    'hideYAxis'?: boolean;
    'hideYTicks'?: boolean;
    'inverse'?: boolean;
    'legend'?: boolean;
    'legendFontSize'?: number;
    'legendWidth'?: number;
    'linearDomain'?: string;
    'linearMetric'?: string;
    'linearTickFormat'?: string;
    'marginBottom'?: number;
    'marginLeft'?: number;
    'marginRight'?: number;
    'marginTop'?: number;
    'maxBarWidth'?: number;
    'onStv-stacked-bar-chart-loaded'?: (event: CustomEvent<any>) => void;
    'ordinalMetric'?: string;
    'orientation'?: string;
    'responsive'?: boolean;
    'seriesMetric'?: string;
    'tooltips'?: boolean;
    'xLabel'?: string;
    'xTickSize'?: number;
    'yLabel'?: string;
    'yTickSize'?: number;
  }

  interface IntrinsicElements {
    'stv-bar-chart': StvBarChart;
    'stv-line-chart': StvLineChart;
    'stv-pie-chart': StvPieChart;
    'stv-stacked-bar-chart': StvStackedBarChart;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'stv-bar-chart': LocalJSX.StvBarChart & JSXBase.HTMLAttributes<HTMLStvBarChartElement>;
      'stv-line-chart': LocalJSX.StvLineChart & JSXBase.HTMLAttributes<HTMLStvLineChartElement>;
      'stv-pie-chart': LocalJSX.StvPieChart & JSXBase.HTMLAttributes<HTMLStvPieChartElement>;
      'stv-stacked-bar-chart': LocalJSX.StvStackedBarChart & JSXBase.HTMLAttributes<HTMLStvStackedBarChartElement>;
    }
  }
}


